
[package]
name = 'minui'
version = '0.1.0'
edition = '2021'

[dependencies]
napi = { version = '2.10.2', default-features = false, features = [
	'napi4',
	"tokio_rt"
] }
napi-derive = '2.9.3'
tokio = { version = "1", features = ["full"] }
[dependencies.raylib]
git = "https://github.com/coffee-is-power/raylib-rs.git"
rev = "7fbb49f1e6b8f862567d588e7a9ebaad815dde23"

[lib]
crate-type = [
	'cdylib',
]

[build-dependencies]
napi-build = '2.0.1'
